-- 코드를 입력하세요
SELECT info.INGREDIENT_TYPE, SUM(half.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF half INNER JOIN ICECREAM_INFO info
ON half.FLAVOR = info.FLAVOR
GROUP BY info.INGREDIENT_TYPE
ORDER BY SUM(half.TOTAL_ORDER) ASC;
